org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=26.3
minecraft_version_range=[26.3]
neo_version=26.3.0.6-beta

mod_id=galacticraftlegacy
mod_name=Galacticraft Legacy
mod_license=MIT
mod_version=26.3-4.0
mod_group_id=pl.kalishak.galacticraftlegacy
mod_authors=Kalishak
mod_description=Unofficial port of the most popular space travel mod for Minecraft!
