/*
 * Copyright (c) 2026 Kalishak
 *
 * Licensed under the MIT license
 * See LICENSE file for more details
 */

package io.kalishak.galacticraftlegacy.references;

import net.minecraft.core.registries.Registries;
import net.minecraft.resources.ResourceKey;
import net.minecraft.world.item.Item;
import net.minecraft.world.level.block.ColorCollection;

public class GalacticraftItemIds {
    public static final ResourceKey<Item> OXYGEN_MASK = create("oxygen_mask");
    public static final ResourceKey<Item> OXYGEN_GEAR = create("oxygen_gear");
    public static final ResourceKey<Item> LIGHT_OXYGEN_TANK = create("light_oxygen_tank");
    public static final ResourceKey<Item> MEDIUM_OXYGEN_TANK = create("medium_oxygen_tank");
    public static final ResourceKey<Item> HEAVY_OXYGEN_TANK = create("heavy_oxygen_tank");
    public static final ResourceKey<Item> INFINITE_OXYGEN_TANK = create("infinite_oxygen_tank");
    public static final ResourceKey<Item> FREQUENCY_MODULE = create("frequency_module");
    public static final ColorCollection<ResourceKey<Item>> PARACHUTE = createColors("parachute");
    public static final ResourceKey<Item> EMERGENCY_KIT = create("emergency_kit");
    public static final ResourceKey<Item> SHIELD_CONTROLLER = create("shield_controller");
    public static final ResourceKey<Item> PROTO_SHIELD_CONTROLLER = create("proto_shield_controller");
    public static final ResourceKey<Item> TIN_CANISTER = create("tin_canister");
    public static final ResourceKey<Item> COPPER_CANISTER = create("copper_canister");
    public static final ResourceKey<Item> FLUID_TANK = create("fluid_tank");
    public static final ResourceKey<Item> SENSOR_LEN = create("sensor_len");
    public static final ResourceKey<Item> SENSOR_GLASSES = create("sensor_glasses");
    public static final ResourceKey<Item> OXYGEN_VENT = create("oxygen_vent");
    public static final ResourceKey<Item> OXYGEN_FAN = create("oxygen_fan");
    public static final ResourceKey<Item> OXYGEN_CONCENTRATOR = create("oxygen_concentrator");
    public static final ResourceKey<Item> T1_ROCKET_ENGINE = create("t1_rocket_engine");
    public static final ResourceKey<Item> T1_ROCKET_BOOSTER = create("t1_rocket_booster");
    public static final ResourceKey<Item> HEAVY_DUTY_PLATE = create("heavy_duty_plate");
    public static final ResourceKey<Item> ROCKET_NOSE_CONE = create("rocket_nose_cone");
    public static final ResourceKey<Item> ROCKET_FIN = create("rocket_fin");
    public static final ResourceKey<Item> STEEL_POLE = create("steel_pole");
    public static final ResourceKey<Item> CANVAS = create("canvas");
    public static final ResourceKey<Item> BUGGY_WHEEL = create("buggy_wheel");
    public static final ResourceKey<Item> BUGGY_SEAT = create("buggy_seat");
    public static final ResourceKey<Item> BUGGY_STORAGE_BOX = create("buggy_storage_box");
    public static final ResourceKey<Item> BUGGY = create("buggy");
    public static final ResourceKey<Item> SINGLE_SOLAR_MODULE = create("single_solar_module");
    public static final ResourceKey<Item> FULL_SOLAR_PANEL = create("full_solar_panel");
    public static final ResourceKey<Item> RAW_SILICON = create("raw_silicon");
    public static final ResourceKey<Item> SOLAR_WAFER = create("solar_wafer");
    public static final ResourceKey<Item> BASIC_WAFER = create("basic_wafer");
    public static final ResourceKey<Item> ADVANCED_WAFER = create("advanced_wafer");
    public static final ResourceKey<Item> AMBIENT_THERMAL_CONTROLLER = create("ambient_thermal_controller");
    public static final ResourceKey<Item> DEHYDRATED_APPLE = create("dehydrated_apple");
    public static final ResourceKey<Item> DEHYDRATED_CARROT = create("dehydrated_carrot");
    public static final ResourceKey<Item> DEHYDRATED_MELON = create("dehydrated_melon");
    public static final ResourceKey<Item> DEHYDRATED_PUMPKIN = create("dehydrated_pumpkin");
    public static final ResourceKey<Item> DEHYDRATED_POTATO = create("dehydrated_potato");
    public static final ResourceKey<Item> DEHYDRATED_BEETROOT = create("dehydrated_beetroot");
    public static final ResourceKey<Item> CANNED_BEEF = create("canned_beef");
    public static final ResourceKey<Item> CHEESE_SLICE = create("cheese_slice");
    public static final ResourceKey<Item> BURGER_BUN = create("burger_bun");
    public static final ResourceKey<Item> RAW_GROUND_BEEF = create("raw_ground_beef");
    public static final ResourceKey<Item> BEEF_PATTY = create("beef_patty");
    public static final ResourceKey<Item> CHEESEBURGER = create("cheeseburger");
    public static final ResourceKey<Item> BATTERY = create("battery");
    public static final ResourceKey<Item> INFINITE_BATTERY = create("infinite_battery");
    public static final ResourceKey<Item> ATOMIC_BATTERY = create("atomic_battery");
    public static final ResourceKey<Item> THROWABLE_METEOR_CHUNK = create("throwable_meteor_chunk");
    public static final ResourceKey<Item> CHEESE_CHUNK = create("cheese_chunk");
    public static final ResourceKey<Item> RAW_METEORIC_IRON = create("raw_meteoric_iron");
    public static final ResourceKey<Item> SAPPHIRE = create("sapphire");
    public static final ResourceKey<Item> FLAG = create("flag");
    public static final ResourceKey<Item> PRE_LAUNCH_CHECKLIST = create("pre_launch_checklist");
    public static final ResourceKey<Item> DUNGEON_LOCATOR = create("dungeon_locator");
    public static final ResourceKey<Item> FRAGMENTED_CARBON = create("fragmented_carbon");
    public static final ResourceKey<Item> RAW_DESH = create("raw_desh");
    public static final ResourceKey<Item> DESH_STICK = create("desh_stick");
    public static final ResourceKey<Item> SLIMELING_INVENTORY_BAG = create("slimeling_bag");
    public static final ResourceKey<Item> FLUID_MANIPULATOR = create("fluid_manipulator");
    public static final ResourceKey<Item> GRAPPLE_GUN = create("grapple_gun");
    public static final ResourceKey<Item> ASTRO_MINER = create("astro_miner");
    public static final ResourceKey<Item> HEAVY_ROCKET_ENGINE = create("heavy_rocket_engine");
    public static final ResourceKey<Item> HEAVY_ROCKET_FINS = create("heavy_rocket_fins");
    public static final ResourceKey<Item> IRON_SHARD = create("iron_shard");
    public static final ResourceKey<Item> TITANIUM_SHARD = create("titanium_shard");
    public static final ResourceKey<Item> THERMAL_CLOTH = create("thermal_cloth");
    public static final ResourceKey<Item> BEAM_CORE = create("beam_core");
    public static final ResourceKey<Item> TITANIUM_DUST = create("titanium_dust");
    public static final ResourceKey<Item> ATMOSPHERIC_VALVE = create("atmospheric_valve");
    public static final ResourceKey<Item> HEAVY_NOSE_CONE = create("heavy_nose_cone");
    public static final ResourceKey<Item> ORION_DRIVE = create("orion_drive");
    public static final ResourceKey<Item> STRANGE_SEEDS = create("strange_seeds");
    public static final ResourceKey<Item> RADIOISOTOPE_CORE = create("radioisotope_core");
    public static final ResourceKey<Item> ISOTHERMAL_FABRIC = create("isothermal_fabric");
    public static final ResourceKey<Item> SOLAR_DUST = create("solar_dust");
    public static final ResourceKey<Item> SOLAR_ARRAY_PANEL = create("solar_array_panel");
    public static final ResourceKey<Item> SOLAR_ARRAY_WAFER = create("solar_array_wafer");
    public static final ResourceKey<Item> MOON_DUNGEON_KEY = create("moon_dungeon_key");
    public static final ResourceKey<Item> MARS_DUNGEON_KEY = create("mars_dungeon_key");
    public static final ResourceKey<Item> VENUS_DUNGEON_KEY = create("venus_dungeon_key");
    public static final ResourceKey<Item> OIL_BUCKET = create("oil_bucket");
    public static final ResourceKey<Item> FUEL_BUCKET = create("fuel_bucket");
    public static final ResourceKey<Item> BACTERIAL_SLUDGE_BUCKET = create("bacterial_sludge_bucket");
    public static final ResourceKey<Item> SULFURIC_ACID_BUCKET = create("sulfuric_acid_bucket");
    public static final ResourceKey<Item> NASA_WORKBENCH_SCHEMATIC = create("schematic");
    public static final ResourceKey<Item> STEEL_HELMET = create("steel_helmet");
    public static final ResourceKey<Item> STEEL_CHESTPLATE = create("steel_chestplate");
    public static final ResourceKey<Item> STEEL_LEGGINGS = create("steel_leggings");
    public static final ResourceKey<Item> STEEL_BOOTS = create("steel_boots");
    public static final ResourceKey<Item> STEEL_PICKAXE = create("steel_pickaxe");
    public static final ResourceKey<Item> STEEL_AXE = create("steel_axe");
    public static final ResourceKey<Item> STEEL_SHOVEL = create("steel_shovel");
    public static final ResourceKey<Item> STEEL_HOE = create("steel_hoe");
    public static final ResourceKey<Item> STEEL_SWORD = create("steel_sword");
    public static final ResourceKey<Item> STEEL_SPEAR = create("steel_spear");
    public static final ResourceKey<Item> STEEL_HORSE_ARMOR = create("steel_horse_armor");
    public static final ResourceKey<Item> STEEL_NAUTILUS_ARMOR = create("steel_nautilus_armor");
    public static final ResourceKey<Item> DESH_HELMET = create("desh_helmet");
    public static final ResourceKey<Item> DESH_CHESTPLATE = create("desh_chestplate");
    public static final ResourceKey<Item> DESH_LEGGINGS = create("desh_leggings");
    public static final ResourceKey<Item> DESH_BOOTS = create("desh_boots");
    public static final ResourceKey<Item> DESH_PICKAXE = create("desh_pickaxe");
    public static final ResourceKey<Item> DESH_AXE = create("desh_axe");
    public static final ResourceKey<Item> DESH_SHOVEL = create("desh_shovel");
    public static final ResourceKey<Item> DESH_HOE = create("desh_hoe");
    public static final ResourceKey<Item> DESH_SWORD = create("desh_sword");
    public static final ResourceKey<Item> DESH_SPEAR = create("desh_spear");
    public static final ResourceKey<Item> THERMAL_CAP = create("thermal_cap");
    public static final ResourceKey<Item> THERMAL_SHIRT = create("thermal_shirt");
    public static final ResourceKey<Item> THERMAL_LEGGINGS = create("thermal_leggings");
    public static final ResourceKey<Item> THERMAL_SOCKS = create("thermal_socks");
    public static final ResourceKey<Item> TITANIUM_HELMET = create("titanium_helmet");
    public static final ResourceKey<Item> TITANIUM_CHESTPLATE = create("titanium_chestplate");
    public static final ResourceKey<Item> TITANIUM_LEGGINGS = create("titanium_leggings");
    public static final ResourceKey<Item> TITANIUM_BOOTS = create("titanium_boots");
    public static final ResourceKey<Item> TITANIUM_PICKAXE = create("titanium_pickaxe");
    public static final ResourceKey<Item> TITANIUM_AXE = create("titanium_axe");
    public static final ResourceKey<Item> TITANIUM_SHOVEL = create("titanium_shovel");
    public static final ResourceKey<Item> TITANIUM_HOE = create("titanium_hoe");
    public static final ResourceKey<Item> TITANIUM_SWORD = create("titanium_sword");
    public static final ResourceKey<Item> TITANIUM_SPEAR = create("titanium_spear");
    public static final ResourceKey<Item> ISOTHERMAL_CAP = create("isothermal_cap");
    public static final ResourceKey<Item> ISOTHERMAL_SHIRT = create("isothermal_shirt");
    public static final ResourceKey<Item> ISOTHERMAL_LEGGINGS = create("isothermal_leggings");
    public static final ResourceKey<Item> ISOTHERMAL_SOCKS = create("isothermal_socks");
    public static final ResourceKey<Item> COMPRESSED_COPPER = create("compressed_copper");
    public static final ResourceKey<Item> COMPRESSED_TIN = create("compressed_tin");
    public static final ResourceKey<Item> COMPRESSED_ALUMINUM = create("compressed_aluminum");
    public static final ResourceKey<Item> COMPRESSED_STEEL = create("compressed_steel");
    public static final ResourceKey<Item> COMPRESSED_BRONZE = create("compressed_bronze");
    public static final ResourceKey<Item> COMPRESSED_IRON = create("compressed_iron");
    public static final ResourceKey<Item> COMPRESSED_METEORIC_IRON = create("compressed_meteoric_iron");
    public static final ResourceKey<Item> T2_HEAVY_DUTY_PLATE = create("heavy_duty_plate_t2");
    public static final ResourceKey<Item> COMPRESSED_DESH = create("compressed_desh");
    public static final ResourceKey<Item> T3_HEAVY_DUTY_PLATE = create("heavy_duty_plate_t3");
    public static final ResourceKey<Item> COMPRESSED_TITANIUM = create("compressed_titanium");
    public static final ResourceKey<Item> STEEL_INGOT = create("steel_ingot");
    public static final ResourceKey<Item> RAW_STEEL = create("raw_steel");
    public static final ResourceKey<Item> STEEL_NUGGET = create("steel_nugget");
    public static final ResourceKey<Item> TIN_INGOT = create("tin_ingot");
    public static final ResourceKey<Item> RAW_TIN = create("raw_tin");
    public static final ResourceKey<Item> ALUMINUM_INGOT = create("aluminum_ingot");
    public static final ResourceKey<Item> RAW_ALUMINUM = create("raw_aluminum");
    public static final ResourceKey<Item> RAW_TITANIUM = create("raw_titanium");
    public static final ResourceKey<Item> METEORIC_IRON_INGOT = create("meteoric_iron_ingot");
    public static final ResourceKey<Item> DESH_INGOT = create("desh_ingot");
    public static final ResourceKey<Item> DESH_NUGGET = create("desh_nugget");
    public static final ResourceKey<Item> TITANIUM_INGOT = create("titanium_ingot");
    public static final ResourceKey<Item> TITANIUM_NUGGET = create("titanium_nugget");
    public static final ResourceKey<Item> LEAD_INGOT = create("lead_ingot");
    public static final ResourceKey<Item> RAW_LEAD = create("raw_lead");
    public static final ResourceKey<Item> WRENCH = create("wrench");
    public static final ResourceKey<Item> STICKY_DESH_PICKAXE = create("sticky_desh_pickaxe");
    public static final ResourceKey<Item> VOLCANIC_PICKAXE = create("volcanic_pickaxe");
    public static final ResourceKey<Item> EVOLVED_SKELETON_SPAWN_EGG = create("evolved_skeleton_spawn_egg");
    public static final ResourceKey<Item> EVOLVED_ZOMBIE_SPAWN_EGG = create("evolved_zombie_spawn_egg");
    
    private static ResourceKey<Item> create(String name) {
        return Constants.key(Registries.ITEM, name);
    }

    private static ColorCollection<ResourceKey<Item>> createColors(String baseName) {
        return ColorCollection.prefixWithColor(ColorCollection.create(baseName)).map(GalacticraftItemIds::create);
    }
}