/*
 * Copyright (c) 2026 Kalishak
 *
 * Licensed under the MIT license
 * See LICENSE file for more details
 */

package io.kalishak.galacticraftlegacy.references;

import net.minecraft.core.registries.Registries;
import net.minecraft.references.BlockItemId;
import net.minecraft.world.level.block.ColorCollection;
import net.minecraft.world.level.block.WeatheringCopperCollection;

public final class GalacticraftBlockItemIds {
    public static final BlockItemId UNLIT_TORCH = create("unlit_torch");
    public static final BlockItemId UNLIT_WALL_TORCH = create("unlit_wall_torch");
    public static final BlockItemId UNLIT_COPPER_TORCH = create("unlit_copper_torch");
    public static final BlockItemId UNLIT_COPPER_WALL_TORCH = create("unlit_copper_wall_torch");
    public static final BlockItemId UNLIT_LANTERN = create("unlit_lantern");
    public static final WeatheringCopperCollection<BlockItemId> UNLIT_COPPER_LANTERN = createWeatheringCopper("unlit_copper_lantern");
    public static final BlockItemId UNLIT_WAXED_COPPER_LANTERN = create("unlit_waxed_copper_lantern");
    public static final BlockItemId LANDING_PAD = create("landing_pad");
    public static final BlockItemId FUELING_PAD = create("fueling_pad");
    public static final BlockItemId OXYGEN_BUBBLE_DISTRIBUTOR = create("oxygen_bubble_distributor");
    public static final BlockItemId OXYGEN_COLLECTOR = create("oxygen_collector");
    public static final BlockItemId OXYGEN_COMPRESSOR = create("oxygen_compressor");
    public static final BlockItemId OXYGEN_DECOMPRESSOR = create("oxygen_decompressor");
    public static final BlockItemId OXYGEN_SEALER = create("oxygen_sealer");
    public static final BlockItemId OXYGEN_DETECTOR = create("oxygen_detector");
    public static final BlockItemId ALUMINUM_WIRE = create("aluminum_wire");
    public static final BlockItemId HEAVY_ALUMINUM_WIRE= create("heavy_aluminum_wire");
    public static final BlockItemId ALUMINUM_WIRE_SWITCH = create("aluminum_wire_switch");
    public static final BlockItemId HEAVY_ALUMINUM_WIRE_SWITCH = create("heavy_aluminum_wire_switch");
    public static final ColorCollection<BlockItemId> FLUID_PIPE = createSimpleColored("fluid_pipe");
    public static final ColorCollection<BlockItemId> COLORED_TINTED_GLASS_PANE = createSimpleColored("tinted_glass_pane");
    public static final BlockItemId TINTED_GLASS_PANE = create("tinted_glass_pane");
    public static final BlockItemId REFINERY = create("refinery");
    public static final BlockItemId FUEL_LOADER = create("fuel_loader");
    public static final BlockItemId CARGO_LOADER = create("cargo_loader");
    public static final BlockItemId CARGO_UNLOADER = create("cargo_unloader");
    public static final BlockItemId NASA_WORKBENCH = create("nasa_workbench");
    public static final BlockItemId COMPACT_NASA_WORKBENCH = create("compact_nasa_workbench");
    public static final BlockItemId TIN_DECORATION_BLOCK = create("tin_decoration_block");
    public static final BlockItemId TIN_DECORATION_SLAB = create("tin_decoration_slab");
    public static final BlockItemId TIN_DECORATION_STAIRS = create("tin_decoration_stairs");
    public static final BlockItemId TIN_DECORATION_WALL = create("tin_decoration_wall");
    public static final BlockItemId TIN_WALL_DECORATION_BLOCK = create("tin_wall_decoration_block");
    public static final BlockItemId TIN_WALL_DECORATION_SLAB = create("tin_wall_decoration_slab");
    public static final BlockItemId TIN_WALL_DECORATION_STAIRS = create("tin_wall_decoration_stairs");
    public static final BlockItemId TIN_ORE = create("tin_ore");
    public static final BlockItemId DEEPSLATE_TIN_ORE = create("deepslate_tin_ore");
    public static final BlockItemId ALUMINUM_ORE = create("aluminum_ore");
    public static final BlockItemId DEEPSLATE_ALUMINUM_ORE = create("deepslate_aluminum_ore");
    public static final BlockItemId SILICON_ORE = create("silicon_ore");
    public static final BlockItemId DEEPSLATE_SILICON_ORE = create("deepslate_silicon_ore");
    public static final BlockItemId TIN_BLOCK = create("tin_block");
    public static final BlockItemId RAW_TIN_BLOCK = create("raw_tin_block");
    public static final BlockItemId ALUMINUM_BLOCK = create("aluminum_block");
    public static final BlockItemId RAW_ALUMINUM_BLOCK = create("raw_aluminum_block");
    public static final BlockItemId RAW_SILICON_BLOCK = create("raw_silicon_block");
    public static final BlockItemId METEORIC_IRON_BLOCK = create("meteoric_iron_block");
    public static final BlockItemId RAW_METEORIC_IRON_BLOCK = create("raw_meteoric_iron_block");
    public static final BlockItemId AIR_LOCK = create("air_lock");
    public static final BlockItemId AIR_LOCK_FRAME = create("air_lock_frame");
    public static final BlockItemId VACUUM_CLEAR_GLASS = create("vacuum_clear_glass");
    public static final BlockItemId VACUUM_GLASS = create("vacuum_glass");
    public static final BlockItemId VACUUM_STRONG_GLASS = create("");
    public static final BlockItemId MAGNETIC_CRAFTING_TABLE = create("magnetic_crafting_table");
    public static final BlockItemId SEALED_ALUMINUM_WIRE = create("sealed_aluminum_wire");
    public static final BlockItemId SEALED_HEAVY_ALUMINUM_WIRE = create("sealed_heavy_aluminum_wire");
    public static final BlockItemId SEALED_FLUID_PIPE = create("sealed_fluid_pipe");
    public static final BlockItemId PARACHEST = create("parachest");
    public static final BlockItemId PARACHEST_SINGLE = create("parachest_single");
    public static final BlockItemId PARACHEST_DOUBLE = create("parachest_double");
    public static final BlockItemId PARACHEST_TRIPLE = create("parachest_triple");
    public static final BlockItemId BASIC_SOLAR_PANEL = create("basic_solar_panel");
    public static final BlockItemId ADVANCED_SOLAR_PANEL = create("advanced_solar_panel");
    public static final BlockItemId COMMUNICATION_DISH = create("communication_dish");
    public static final BlockItemId OIL = create("oil");
    public static final BlockItemId FUEL = create("fuel");
    public static final BlockItemId OIL_CAULDRON = create("oil_cauldron");
    public static final BlockItemId FUEL_CAULDRON = create("fuel_cauldron");
    public static final BlockItemId COAL_GENERATOR = create("coal_generator");
    public static final BlockItemId COMPRESSOR = create("compressor");
    public static final BlockItemId ELECTRIC_COMPRESSOR = create("electric_compressor");
    public static final BlockItemId CIRCUIT_FABRICATOR = create("circuit_fabricator");
    public static final BlockItemId OXYGEN_STORAGE_MODULE = create("oxygen_storage_module");
    public static final BlockItemId ELECTRIC_FURNACE = create("electric_furnace");
    public static final BlockItemId ELECTRIC_ARC_FURNACE = create("electric_arc_furnace");
    public static final BlockItemId ADVANCED_COMPRESSOR = create("advanced_compressor");
    public static final BlockItemId LIGHTNING_SQUARE_PANEL = create("lightning_square_panel");
    public static final BlockItemId LIGHTNING_SPOTLIGHT_PANEL = create("lightning_spotlight_panel");
    public static final BlockItemId LIGHTNING_LINEAR_PANEL = create("lightning_linear_panel");
    public static final BlockItemId LIGHTNING_SERIAL_PANEL = create("lightning_serial_panel");
    public static final BlockItemId LIGHTNING_TRIANGULAR_PANEL = create("lightning_triangular_panel");
    public static final BlockItemId GLOWSTONE_TORCH = create("glowstone_torch");
    public static final BlockItemId FALLEN_METEOR = create("fallen_meteor");
    public static final BlockItemId MOON_COPPER_ORE = create("moon_copper_ore");
    public static final BlockItemId MOON_TIN_ORE = create("moon_tin_ore");
    public static final BlockItemId MOON_CHEESE_ORE = create("moon_cheese_ore");
    public static final BlockItemId MOON_DIRT = create("moon_dirt");
    public static final BlockItemId MOON_ROCK = create("moon_rock");
    public static final BlockItemId MOON_ROCK_SLAB = create("moon_rock_slab");
    public static final BlockItemId MOON_ROCK_STAIRS = create("moon_rock_stairs");
    public static final BlockItemId MOON_ROCK_WALL = create("moon_rock_wall");
    public static final BlockItemId MOON_TURF = create("moon_turf");
    public static final BlockItemId MOON_SAPPHIRE_ORE = create("moon_sapphire_ore");
    public static final BlockItemId MOON_DUNGEON_BRICKS = create("moon_dungeon_bricks");
    public static final BlockItemId MOON_DUNGEON_BRICK_SLAB = create("moon_dungeon_brick_slab");
    public static final BlockItemId MOON_DUNGEON_BRICK_STAIRS = create("moon_dungeon_brick_stairs");
    public static final BlockItemId MOON_DUNGEON_BRICK_WALL = create("moon_dungeon_brick_wall");
    public static final BlockItemId CHEESE_BLOCK = create("cheese");
    public static final BlockItemId SPIN_THRUSTER = create("spin_thruster");
    public static final BlockItemId DISPLAY_SCREEN = create("display_screen");
    public static final BlockItemId TELEMETRY_UNIT = create("telemetry_unit");
    public static final BlockItemId ARC_LAMP = create("arc_lamp");
    public static final BlockItemId MOON_DUNGEON_CHEST = create("moon_dungeon_chest");
    public static final BlockItemId MARS_DUNGEON_CHEST = create("mars_dungeon_chest");
    public static final BlockItemId VENUS_DUNGEON_CHEST = create("venus_dungeon_chest");
    public static final BlockItemId FLUID_TANK = create("fluid_tank");
    public static final BlockItemId SEALED_REDSTONE_WIRE = create("sealed_redstone_wire");
    public static final BlockItemId SEALED_REDSTONE_REPEATER = create("sealed_redstone_repeater");
    public static final BlockItemId SEALED_REDSTONE_COMPARATOR = create("sealed_redstone_comparator");
    public static final BlockItemId HYDRAULIC_PLATFORM = create("hydraulic_platform");
    public static final BlockItemId EMERGENCY_POST = create("emergency_post");
    public static final BlockItemId GRATING = create("grating");
    public static final BlockItemId MARS_COPPER_ORE = create("mars_copper_ore");
    public static final BlockItemId MARS_TIN_ORE = create("mars_tin_ore");
    public static final BlockItemId MARS_DESH_ORE = create("mars_desh_ore");
    public static final BlockItemId MARS_IRON_ORE = create("mars_iron_ore");
    public static final BlockItemId MARS_COBBLESTONE = create("mars_cobblestone");
    public static final BlockItemId MARS_COBBLESTONE_SLAB = create("mars_cobblestone_slab");
    public static final BlockItemId MARS_COBBLESTONE_STAIRS = create("mars_cobblestone_stairs");
    public static final BlockItemId MARS_COBBLESTONE_WALL = create("mars_cobblestone_wall");
    public static final BlockItemId MARS_FINE_REGOLITH = create("mars_fine_regolith");
    public static final BlockItemId MARS_FINE_REGOLITH_SLAB = create("mars_fine_regolith_slab");
    public static final BlockItemId MARS_FINE_REGOLITH_STAIRS = create("mars_fine_regolith_stairs");
    public static final BlockItemId MARS_REGOLITH = create("mars_fine_regolith");
    public static final BlockItemId MARS_REGOLITH_SLAB = create("mars_regolith_slab");
    public static final BlockItemId MARS_REGOLITH_STAIRS = create("mars_regolith_stairs");
    public static final BlockItemId MARS_DUNGEON_BRICKS = create("mars_dungeon_bricks");
    public static final BlockItemId MARS_DUNGEON_BRICK_SLAB = create("mars_dungeon_brick_slab");
    public static final BlockItemId MARS_DUNGEON_BRICK_STAIRS = create("mars_dungeon_brick_stairs");
    public static final BlockItemId MARS_DUNGEON_BRICK_WALL = create("mars_dungeon_brick_wall");
    public static final BlockItemId DESH_BLOCK = create("desh_block");
    public static final BlockItemId RAW_DESH_BLOCK = create("raw_desh_block");
    public static final BlockItemId MARS_STONE = create("mars_stone");
    public static final BlockItemId MARS_STONE_SLAB = create("mars_stone_slab");
    public static final BlockItemId MARS_STONE_STAIRS = create("mars_stone_stairs");
    public static final BlockItemId MARS_STONE_PRESSURE_PLATE = create("mars_stone_pressure_plate");
    public static final BlockItemId MARS_STONE_BUTTON = create("mars_stone_button");
    public static final BlockItemId CAVERNOUS_VINES = create("cavernous_vines");
    public static final BlockItemId SLIMELING_EGG = create("slimeling_egg");
    public static final BlockItemId CREEPER_EGG = create("crepper_egg");
    public static final BlockItemId TERRAFORMER = create("terraformer");
    public static final BlockItemId CRYOGENIC_CHAMBER = create("cryogenic_chamber");
    public static final BlockItemId LAUNCH_CONTROLLER = create("launch_controller");
    public static final BlockItemId GAS_LIQUEFIER = create("gas_liquefier");
    public static final BlockItemId METHANE_SYNTHESIZER = create("methane_synthesizer");
    public static final BlockItemId WATER_ELECTROLYZER = create("water_electrolyzer");
    public static final BlockItemId ASTEROID_ROCK = create("asteroid_rock");
    public static final BlockItemId ASTEROID_ROCK_SLAB = create("asteroid_rock_slab");
    public static final BlockItemId ASTEROID_ROCK_STAIRS = create("asteroid_rock_stairs");
    public static final BlockItemId ASTEROID_ROCK_WALL = create("asteroid_rock_wall");
    public static final BlockItemId ASTEROID_FINE_ROCK = create("asteroid_fine_rock");
    public static final BlockItemId ASTEROID_FINE_ROCK_SLAB = create("asteroid_fine_rock_slab");
    public static final BlockItemId ASTEROID_FINE_ROCK_STAIRS = create("asteroid_fine_rock_stairs");
    public static final BlockItemId ASTEROID_STONE = create("asteroid_stone");
    public static final BlockItemId ASTEROID_STONE_SLAB = create("asteroid_stone_slab");
    public static final BlockItemId ASTEROID_STONE_STAIRS = create("asteroid_stone_stairs");
    public static final BlockItemId ASTEROID_ALUMINUM_ORE = create("asteroid_aluminum_ore");
    public static final BlockItemId ASTEROID_TITANIUM_ORE = create("asteroid_titanium_ore");
    public static final BlockItemId ASTEROID_IRON_ORE = create("asteroid_iron_ore");
    public static final BlockItemId DARK_DECORATION_BLOCK = create("dark_decoration_block");
    public static final BlockItemId DARK_DECORATION_SLAB = create("dark_decoration_slab");
    public static final BlockItemId DARK_DECORATION_STAIRS = create("dark_decoration_stairs");
    public static final BlockItemId DARK_DECORATION_WALL = create("dark_decoration_wall");
    public static final BlockItemId TITANIUM_BLOCK = create("titanium_block");
    public static final BlockItemId RAW_TITANIUM_BLOCK = create("raw_titanium_block");
    public static final BlockItemId WALKWAY = create("walkway");
    public static final BlockItemId ALUMINUM_WIRE_WALKWAY = create("aluminum_wire_walkway");
    public static final BlockItemId HEAVY_ALUMINUM_WIRE_WALKWAY = create("heavy_aluminum_wire_walkway");
    public static final BlockItemId FLUID_PIPE_WALKWAY = create("fluid_pipe_walkway");
    public static final BlockItemId REDSTONE_WIRE_WALKWAY = create("redstone_wire_walkway");
    public static final BlockItemId ENERGY_BEAM_REFLECTOR = create("energy_beam_reflector");
    public static final BlockItemId ENERGY_BEAM_RECEIVER = create("energy_beam_receiver");
    public static final BlockItemId SHORT_RANGE_TELEPAD = create("short_range_telepad");
    public static final BlockItemId DENSE_ICE = create("dense_ice");
    public static final BlockItemId ASTRO_MINER_BASE = create("astro_miner_base");
    public static final BlockItemId VENUS_SOFT_ROCK = create("venus_soft_rock");
    public static final BlockItemId VENUS_SOFT_ROCK_SLAB = create("venus_soft_rock_slab");
    public static final BlockItemId VENUS_SOFT_ROCK_STAIRS = create("venus_soft_rock_stairs");
    public static final BlockItemId VENUS_SOFT_ROCK_WALL = create("venus_soft_rock_wall");
    public static final BlockItemId CHISELED_VENUS_SOFT_ROCK = create("chiseled_venus_soft_rock");
    public static final BlockItemId VENUS_HARD_ROCK = create("venus_hard_rock");
    public static final BlockItemId VENUS_HARD_ROCK_SLAB = create("venus_hard_rock_slab");
    public static final BlockItemId VENUS_HARD_ROCK_STAIRS = create("venus_hard_rock_stairs");
    public static final BlockItemId VENUS_HARD_ROCK_WALL = create("venus_hard_rock_wall");
    public static final BlockItemId CHISELED_VENUS_HARD_ROCK = create("chiseled_venus_hard_rock");
    public static final BlockItemId VENUS_VOLCANIC_ROCK = create("venus_volcanic_rock");
    public static final BlockItemId VENUS_VOLCANIC_ROCK_SLAB = create("venus_volcanic_rock_slab");
    public static final BlockItemId VENUS_VOLCANIC_ROCK_STAIRS = create("venus_volcanic_rock_stairs");
    public static final BlockItemId VENUS_VOLCANIC_ROCK_WALL = create("venus_volcanic_rock_wall");
    public static final BlockItemId CHISELED_VENUS_VOLCANIC_ROCK = create("chiseled_venus_volcanic_rock");
    public static final BlockItemId PUMICE = create("pumice");
    public static final BlockItemId VENUS_DUNGEON_BRICKS = create("venus_dungeon_bricks");
    public static final BlockItemId VENUS_DUNGEON_BRICK = create("venus_dungeon_brick");
    public static final BlockItemId VENUS_DUNGEON_BRICK_SLAB = create("venus_dungeon_brick_slab");
    public static final BlockItemId VENUS_DUNGEON_BRICK_STAIRS = create("venus_dungeon_brick_stairs");
    public static final BlockItemId VENUS_DUNGEON_BRICK_WALL = create("venus_dungeon_brick_wall");
    public static final BlockItemId DEEP_VENUS_DUNGEON_BRICKS = create("deep_venus_dungeon_bricks");
    public static final BlockItemId DEEP_VENUS_DUNGEON_BRICK_SLAB = create("deep_venus_dungeon_brick_slab");
    public static final BlockItemId DEEP_VENUS_DUNGEON_BRICK_STAIRS = create("deep_venus_dungeon_brick_stairs");
    public static final BlockItemId DEEP_VENUS_DUNGEON_BRICK_WALL = create("deep_venus_dungeon_brick_wall");
    public static final BlockItemId VENUS_ALUMINUM_ORE = create("venus_aluminum_ore");
    public static final BlockItemId VENUS_COPPER_ORE = create("venus_copper_ore");
    public static final BlockItemId VENUS_LEAD_ORE = create("venus_lead_ore");
    public static final BlockItemId VENUS_QUARTZ_ORE = create("venus_quartz_ore");
    public static final BlockItemId VENUS_SILICON_ORE = create("venus_silicon_ore");
    public static final BlockItemId VENUS_SOLAR_ORE = create("venus_solar_ore");
    public static final BlockItemId VENUS_SULFUR_ORE = create("venus_sulfur_ore");
    public static final BlockItemId VAPOR_SPROUT = create("vapor_sprout");
    public static final BlockItemId WEB_STRING = create("web_string");
    public static final BlockItemId WEB_GLOWSTONE_STRING = create("web_glowstone_string");
    public static final BlockItemId GEOTHERMAL_GENERATOR = create("geothermal_generator");
    public static final BlockItemId CRASHED_PROBE = create("crashed_probe");
    public static final BlockItemId SCORCHED_VENUS_ROCK = create("venus_volcanic_rock");
    public static final BlockItemId SCORCHED_VENUS_ROCK_SLAB = create("venus_volcanic_rock_slab");
    public static final BlockItemId SCORCHED_VENUS_ROCK_STAIRS = create("venus_volcanic_rock_stairs");
    public static final BlockItemId SCORCHED_VENUS_ROCK_WALL = create("venus_volcanic_rock_wall");
    public static final BlockItemId CHISELED_SCORCHED_VENUS_ROCK = create("chiseled_venus_volcanic_rock");
    public static final BlockItemId SOLAR_ARRAY_MODULE = create("solar_array_module");
    public static final BlockItemId SOLAR_ARRAY_CONTROLLER = create("solar_array_controller");
    public static final BlockItemId SPACE_STATION = create("space_station");
    public static final BlockItemId LASER_TURRET = create("laser_turret");

    private static WeatheringCopperCollection<BlockItemId> createWeatheringCopper(String baseName) {
        return WeatheringCopperCollection.prefixWithState(WeatheringCopperCollection.create(baseName)).map(GalacticraftBlockItemIds::create);
    }

    private static BlockItemId create(String name) {
        return new BlockItemId(
                Constants.key(Registries.BLOCK, name),
                Constants.key(Registries.ITEM, name)
        );
    }

    private static ColorCollection<BlockItemId> createSimpleColored(String baseName) {
        return ColorCollection.prefixWithColor(ColorCollection.create(baseName)).map(GalacticraftBlockItemIds::create);
    }
}
